# Desarrollo Web en Entorno Servidor
# Antonio J. Sánchez
# curso 2024|25

version: '3'

services:
  #
  # WEB
  web:
    container_name: dwes-web
    build: .
    volumes:
      - ./html:/var/www/html
    ports:
      - '80:80'
    links:
      - 'db:database'

  #
  # DATABASE
  db:
    image: 'mariadb:latest'
    container_name: dwes-bdat
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: todolist
    ports:
      - '3306:3306'

  #
  # PHPMYADMIN
  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: dwes-phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=root
